### ISSUE TITLE
Problems displaying output from Select-Object -Property *

### ISSUE THREAD

**Issue by cantoris** [PowerShell/GraphicalTools#26]
Get-Process | Select * | Out-GridView
Fails with "Process has exited, so the requested information is not available."
(System.InvalidOperationException,OutGridView.Cmdlet.OutGridViewCmdletCommand)
Works fine without the Select *.

Reproduced on Win10x64 b1809 and b1903 using PS 6.2.2 and 7.0.0 Preview 2.  Module is v0.1.1.

Trying the same with Get-Service | Select *  opens a GridView output window but its contents are entirely black.  Thanks for reading.

**Comment by TylerLeonhardt** [comment]
@cantoris I can't repro this. I just ran `Get-Process | Select * | Out-GridView` and although it's very slow because of the amount of columns and data, it does open for me.

What you're seeing is very likely the result of giving it too much data. We should figure out how to handle large amounts of data like this.

**Comment by golovini** [comment]
$a = Get-ChildItem c:\users | select name, length | Out-GridView -OutputMode Single
Doesn't work: no OK(Export) Cancel buttons (PSVersion: 7.0.0-preview.2).

**Comment by TheTaylorLee** [comment]
Errors out for me as well. Works fine with limited properties. This is the error I get...

`PSMessageDetails      :
Exception             : System.InvalidOperationException: Process has exited, so the requested information is not available.
                           at System.Diagnostics.Process.EnsureState(State state)
                           at System.Diagnostics.Process.ToString()
                           at OutGridView.Cmdlet.TypeGetter.<>c__DisplayClass3_0.<CastObjectToDataTableRow>b__0(PSPropertyExpression x) in
                        D:\a\1\s\src\Microsoft.PowerShell.GraphicalTools\TypeGetter.cs:line 86
                           at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
                           at System.Linq.Enumerable.SelectListIterator`2.ToList()
                           at OutGridView.Cmdlet.TypeGetter.CastObjectToDataTableRow(PSObject ps, FormatViewDefinition fvd, Int32 objectIndex) in
                        D:\a\1\s\src\Microsoft.PowerShell.GraphicalTools\TypeGetter.cs:line 89
                           at OutGridView.Cmdlet.TypeGetter.<>c__DisplayClass6_0.<CastObjectsToTableView>b__0(PSObject ps, Int32 idx) in
                        D:\a\1\s\src\Microsoft.PowerShell.GraphicalTools\TypeGetter.cs:line 182
                           at System.Linq.Enumerable.SelectIterator[TSource,TResult](IEnumerable`1 source, Func`3 selector)+MoveNext()
                           at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
                           at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
                           at OutGridView.Cmdlet.TypeGetter.CastObjectsToTableView(List`1 psObjects, FormatViewDefinition fvd) in
                        D:\a\1\s\src\Microsoft.PowerShell.GraphicalTools\TypeGetter.cs:line 182
                           at OutGridView.Cmdlet.OutGridViewCmdletCommand.EndProcessing() in
                        D:\a\1\s\src\Microsoft.PowerShell.GraphicalTools\OutGridviewCmdletCommand.cs:line 142
                           at System.Management.Automation.Cmdlet.DoEndProcessing()
                           at System.Management.Automation.CommandProcessorBase.Complete()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Out-GridView], InvalidOperationException
FullyQualifiedErrorId : System.InvalidOperationException,OutGridView.Cmdlet.OutGridViewCmdletCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      :
PipelineIterationInfo : {}`

Thanks,

**Comment by lahell** [comment]
I may have narrowed it down to explorer and wslhost.

```
PS C:\> Get-Process wslhost | select * | Out-GridView
Out-GridView: The following exception occurred while retrieving the string: "Process has exited, so the requested information is not available."
PS C:\> $process = Get-Process explorer | select *
PS C:\> $process | Out-GridView
Out-GridView: The following exception occurred while retrieving the string: "Process has exited, so the requested information is not available."
```

This works for me:

```
Get-Process | where Name -notin 'explorer', 'wslhost' | select * | Out-GridView
```

**Comment by lahell** [comment]
Parent property of explorer and wslhost seems to be the culprit.

```
PS C:\> Get-Process explorer | select Parent | Out-GridView
Out-GridView: The following exception occurred while retrieving the string: "Process has exited, so the requested information is not available."
PS C:\> Get-Process wslhost | select Parent | Out-GridView
Out-GridView: The following exception occurred while retrieving the string: "Process has exited, so the requested information is not available."
```

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
