### ISSUE TITLE
Out-ConsoleGridView does not accept XML data

### ISSUE THREAD

**Issue by jasper-zanjani** [PowerShell/GraphicalTools#97]
While manipulating XML data and testing `Out-ConsoleGridView` (Powershell 7.0.0 on Windows 10.0.19603), I noticed that the cmdlet appears to demand data of a certain datatype. For testing, a sample XML file can be found [here](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms762271(v=vs.85) "sample.xml").
```powershell
[xml]$xml = Get-Content '.\sample.xml'
```
Tabular output from `$xml` can be viewed in the terminal
```powershell
$xml.catalog.book
```

Output:
```
id           : bk101
author       : Gambardella, Matthew
title        : XML Developer's Guide
genre        : Computer
price        : 44.95
publish_date : 2000-10-01
description  : An in-depth look at creating applications 
                     with XML.

id           : bk102
...
```
Piping to `Out-GridView` produces expected output
```powershell
$xml.catalog.book | Out-GridView
```

Output:

![out-gridview](https://user-images.githubusercontent.com/8889926/81102219-4f71dc00-8edd-11ea-98e3-02674e1a96e3.png 'Output of `$xml.catalog.book | Out-GridView`')
---
However, piping to `Out-ConsoleGridView` produces an error
```powershell
$xml.catalog.book | Out-ConsoleGridView
```
![out-consolegridview](https://user-images.githubusercontent.com/8889926/81102446-a4aded80-8edd-11ea-8177-31c5a7a57909.png 'Output of `$xml.catalog.book | Out-ConsoleGridView')

**Comment by TylerLeonhardt** [comment]
hmm I can't seem to repro this...

![image](https://user-images.githubusercontent.com/2644648/81239371-874e5180-8fb9-11ea-9e83-4fe9efbb1acc.png)

I had it repro'ing once but that PowerShell instance seemed to be corrupted in some way...

It might be that the next version of gui.cs that we depend on will have more stability here.

**Comment by jasper-zanjani** [comment]
I just updated to 7.0.1 and I am getting the same error, any new ideas?

**Comment by TylerLeonhardt** [comment]
Can you paste the output of `Get-Error`?

**Comment by TylerLeonhardt** [comment]
gentle ping on this

**Comment by jasper-zanjani** [comment]
I just went through the same steps, creating an XML object from the same test file above.
```
jaspe PS> $data.catalog.book | Out-ConsoleGridView
Out-ConsoleGridView: Length cannot be less than zero. (Parameter 'length')
```
```
Exception             :
    Type       : System.ArgumentOutOfRangeException
    Message    : Length cannot be less than zero. (Parameter 'length')
    ParamName  : length
    TargetSite :
        Name          : Substring
        DeclaringType : string
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.String.Substring(Int32 startIndex, Int32 length)
   at OutGridView.Cmdlet.ConsoleGui.GetPaddedString(List`1 strings, Int32 offset) in
D:\a\1\s\src\Microsoft.PowerShell.ConsoleGuiTools\ConsoleGui.cs:line 320
   at OutGridView.Cmdlet.ConsoleGui.Start(ApplicationData applicationData) in
D:\a\1\s\src\Microsoft.PowerShell.ConsoleGuiTools\ConsoleGui.cs:line 152
   at OutGridView.Cmdlet.OutConsoleGridViewCmdletCommand.EndProcessing() in
D:\a\1\s\src\Microsoft.PowerShell.ConsoleGuiTools\OutConsoleGridviewCmdletCommand.cs:line 143
   at System.Management.Automation.CommandProcessorBase.Complete()
    Source     : System.Private.CoreLib
    HResult    : -2146233086
CategoryInfo          : NotSpecified: (:) [Out-ConsoleGridView], ArgumentOutOfRangeException
FullyQualifiedErrorId : System.ArgumentOutOfRangeException,OutGridView.Cmdlet.OutConsoleGridViewCmdletCommand
InvocationInfo        :
    MyCommand        : Out-ConsoleGridView
    ScriptLineNumber : 1
    OffsetInLine     : 22
    HistoryId        : 15
    Line             : $data.catalog.book | Out-ConsoleGridView
    PositionMessage  : At line:1 char:22
                       + $data.catalog.book | Out-ConsoleGridView
                       +                      ~~~~~~~~~~~~~~~~~~~
    InvocationName   : Out-ConsoleGridView
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by tig** [comment]
I can repro. I'll take a look.

**Comment by tig** [comment]
Ok, this is beyond my knowledge of PS. What I've found is the cmdlet's `ProcessRecord` method gets called but `InputObject` is null.

**Comment by TylerLeonhardt** [comment]
@tig were your repro steps the same?

**Comment by tig** [comment]
Yes. I grabbed his XML file and tested as he showed.

**Comment by tig** [comment]
@andschwa please prefix title with "OCGV: ".
